### PR TITLE
config merge should override existing values to mimick helm behavior

### PR DESCRIPTION
**Pull request by MathiasGr**

### CODE REVIEW

**Comment by pawelprazak** [comment]
Looks good, I'll just confirm with some unit tests.

**Comment by MathiasGr** [comment]
@pawelprazak Thanks !

Are you working on the unit tests or do you want me to do it?

**Comment by pawelprazak** [comment]
feel free add some tests, that would be awesome, still have some other
tasks on my hands

**Comment by MathiasGr** [comment]
Thank you for this great tool !
And sorry for not writing the tests I’m pretty busy too at the moment.

**Pull request merged**
